amcl:
  ros__parameters:
    use_sim_time: True

    # Interface the AMCL will use to interact with other ROS2 nodes
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: scan
    tf_broadcast: True
    transform_tolerance: 1.0  # AMCL expects to get a transform between "map" and "base_footprint" every 1s
    save_pose_rate: 0.5 # AMCL will regulary save the current position of the robot

    # AMCL will set the initial pose of the robot
    set_initial_pose: True
    initial_pose: 
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    # Configure the Odometry Motion Model for AMCL
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

    # Configure the Sensor Model (Laser Scan) for AMCL
    laser_model_type: "likelihood_field"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    max_beams: 60
    pf_err: 0.05
    pf_z: 0.99
    sigma_hit: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

    # Resampling Algorithm
    resample_interval: 1
    max_particles: 2000
    min_particles: 500
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    update_min_a: 0.25  # Min Angular movement robot has to perform for the update. 0.2 rad 
    update_min_d: 0.25  # Min Linear movement robot has to perform for the update. 0.25 m
