planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: true
    planner_plugins: ["GridBasedDijkstra", "GridBasedAStar"]

    GridBasedDijkstra:
      plugin: "bumperbot_planning::DijkstraPlanner"

    GridBasedAStar:
      plugin: "bumperbot_planning::AStarPlanner"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0 
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.1
      resolution: 0.05  # 5 cm2 cell in real world
      always_send_full_costmap: true
      track_unknown_space: true

      # Order of the layers matter
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      # Name given to our plugin
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local:  true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          max_obstacle_height: 2.0
          marking: true     # marks obstacles detected by the layer in costmap
          clearing: true    # mark free cells
          combination_method: 1 # how the current layer treats the costmap from a layer below
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.55
          cost_scaling_factor: 3.5